const std = @import("std");
const generated_header = @import("../generators/generated_header.zig");
const openapi2zig = @import("../lib.zig");
const test_utils = @import("test_utils.zig");

test "render emits expected header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const header = try generated_header.render(allocator, "0.6.0 (a1b2c3d)");
    defer allocator.free(header);

    try std.testing.expectEqualStrings(
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig 0.6.0 (a1b2c3d)
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
        \\
    , header);
}

test "checksum is deterministic for same content" {
    var gpa = test_utils.createTestAllocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum1 = generated_header.computeChecksum(code);
    const checksum2 = generated_header.computeChecksum(code);

    try std.testing.expectEqual(checksum1, checksum2);
}

test "checksum differs for different content" {
    var gpa = test_utils.createTestAllocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const code1 = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const code2 = "pub const Bar = struct {\n    id: i64,\n};\n";

    const checksum1 = generated_header.computeChecksum(code1);
    const checksum2 = generated_header.computeChecksum(code2);

    try std.testing.expect(checksum1 != checksum2);
}

test "header includes checksum line" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum = generated_header.computeChecksum(code);

    const header = try generated_header.renderWithChecksum(allocator, "0.6.0 (a1b2c3d)", checksum);
    defer allocator.free(header);

    try std.testing.expect(std.mem.indexOf(u8, header, "Checksum:") != null);
    try std.testing.expect(std.mem.indexOf(u8, header, "Changes to this file may cause incorrect behavior") != null);
}

test "checksum can be extracted from rendered header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum = generated_header.computeChecksum(code);

    const header = try generated_header.renderWithChecksum(allocator, "0.6.0 (a1b2c3d)", checksum);
    defer allocator.free(header);

    const extracted = generated_header.extractChecksum(header);
    try std.testing.expect(extracted != null);
    try std.testing.expectEqual(checksum, extracted.?);
}

test "hasChanged returns false when code has not changed" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum = generated_header.computeChecksum(code);

    const header = try generated_header.renderWithChecksum(allocator, "0.6.0 (a1b2c3d)", checksum);
    defer allocator.free(header);

    const full_content = try std.mem.concat(allocator, u8, &.{ header, code });
    defer allocator.free(full_content);

    try std.testing.expect(!generated_header.hasChanged(full_content, code));
}

test "hasChanged returns false when the existing file has CRLF line endings" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    // Simulates a file checked out with core.autocrlf=true, which turns the
    // repo's LF endings into CRLF on disk.
    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum = generated_header.computeChecksum(code);

    const header = try generated_header.renderWithChecksum(allocator, "0.6.0 (a1b2c3d)", checksum);
    defer allocator.free(header);

    const crlf_header = try std.mem.replaceOwned(u8, allocator, header, "\n", "\r\n");
    defer allocator.free(crlf_header);

    const full_content = try std.mem.concat(allocator, u8, &.{ crlf_header, code });
    defer allocator.free(full_content);

    try std.testing.expect(!generated_header.hasChanged(full_content, code));
}

test "hasChanged returns true when code has changed" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const original_code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const checksum = generated_header.computeChecksum(original_code);

    const header = try generated_header.renderWithChecksum(allocator, "0.6.0 (a1b2c3d)", checksum);
    defer allocator.free(header);

    const full_content = try std.mem.concat(allocator, u8, &.{ header, original_code });
    defer allocator.free(full_content);

    const new_code = "pub const Bar = struct {\n    id: i64,\n};\n";
    try std.testing.expect(generated_header.hasChanged(full_content, new_code));
}

test "hasChanged returns true for file without checksum header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const old_header =
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig 0.5.0 (abc1234) on 2026-01-01 00:00:00 UTC
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
        \\
    ;

    const code = "pub const Foo = struct {\n    name: []const u8,\n};\n";
    const full_content = try std.mem.concat(allocator, u8, &.{ old_header, code });
    defer allocator.free(full_content);

    try std.testing.expect(generated_header.hasChanged(full_content, code));
}

test "generateCode output includes generated header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const json =
        \\{
        \\  "openapi": "3.0.0",
        \\  "info": { "title": "fixture", "version": "1.0.0" },
        \\  "paths": {}
        \\}
    ;

    var unified = try openapi2zig.parseToUnified(allocator, json);
    defer unified.deinit(allocator);

    const code = try openapi2zig.generateCode(allocator, unified, .{
        .input_path = "fixture.json",
        .models_only = true,
    });
    defer allocator.free(code);

    try std.testing.expect(std.mem.indexOf(u8, code, "This code was generated by openapi2zig") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "Changes to this file may cause incorrect behavior") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "will be lost if the code is regenerated") != null);
}
