const std = @import("std");
const version_info = @import("build_info");

// The header deliberately carries no generation date. It is prepended to every
// file this tool emits, so a date in it would mean two runs over the same
// document produced different bytes: a regeneration would always show a diff,
// a build system could never cache a step that consumed the output, and a
// release could not be checked by regenerating it. Nothing is lost by leaving
// it out -- the generator version and its commit say exactly what produced the
// file, `Checksum` says exactly what is below, and when the file was written
// is what version control is for.

pub fn render(allocator: std.mem.Allocator, version: []const u8) ![]const u8 {
    return try std.fmt.allocPrint(allocator,
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig {s}
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
        \\
    , .{version});
}

pub fn renderWithChecksum(allocator: std.mem.Allocator, version: []const u8, checksum: u64) ![]const u8 {
    return try std.fmt.allocPrint(allocator,
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig {s}
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\//   Checksum: {x}
        \\// </auto-generated>
        \\
        \\
    , .{ version, checksum });
}

/// The version string as it appears in a generated header: the release this
/// tool reports plus the commit it was built from.
pub fn renderVersion(allocator: std.mem.Allocator) ![]const u8 {
    return try std.fmt.allocPrint(allocator, "{s} ({s})", .{ version_info.VERSION, version_info.GIT_COMMIT });
}

pub fn renderFromBuildInfoWithChecksum(allocator: std.mem.Allocator, checksum: u64) ![]const u8 {
    const version = try renderVersion(allocator);
    defer allocator.free(version);
    return try renderWithChecksum(allocator, version, checksum);
}

pub fn renderFromBuildInfo(allocator: std.mem.Allocator) ![]const u8 {
    const version = try renderVersion(allocator);
    defer allocator.free(version);
    return try render(allocator, version);
}

pub fn computeChecksum(code: []const u8) u64 {
    return std.hash.Wyhash.hash(0, code);
}

pub fn extractChecksum(content: []const u8) ?u64 {
    const marker = "//   Checksum: ";
    const start = std.mem.indexOf(u8, content, marker) orelse return null;
    const after = content[start + marker.len ..];
    const end = std.mem.indexOf(u8, after, "\n") orelse after.len;
    const hex_str = std.mem.trim(u8, after[0..end], " \r");
    return std.fmt.parseInt(u64, hex_str, 16) catch null;
}

pub fn hasChanged(existing_content: []const u8, new_code: []const u8) bool {
    const existing_checksum = extractChecksum(existing_content) orelse return true;
    const new_checksum = computeChecksum(new_code);
    return existing_checksum != new_checksum;
}
