const std = @import("std");
const generated_header = @import("../generators/generated_header.zig");
const normalizer = @import("../generators/output_normalizer.zig");

/// Writes generated code to `path`, skipping the write entirely when the file
/// already contains the same code.
///
/// `raw_code` is normalized first so that what lands on disk is already
/// `zig fmt` clean. Without that, running `zig fmt` over the output rewrites it
/// and the file stops matching the code its header checksum describes.
///
/// Change detection compares the checksum recorded in the existing file's
/// `<auto-generated>` header against the checksum of the normalized code. The
/// header itself carries the generator version, so it is deliberately excluded
/// from the checksum: only the generated body decides whether the file needs
/// rewriting.
///
/// `path` may be relative to `cwd` or absolute.
pub fn writeGeneratedFile(
    allocator: std.mem.Allocator,
    io: std.Io,
    cwd: std.Io.Dir,
    path: []const u8,
    raw_code: []const u8,
    force: bool,
) !void {
    const code = try normalizer.normalize(allocator, raw_code);
    defer allocator.free(code);

    if (force) {
        std.log.info("Force flag is set; overwriting '{s}'", .{path});
    } else if (try isUnchanged(allocator, io, cwd, path, code)) {
        std.log.info("Skipping '{s}' (unchanged)", .{path});
        return;
    }

    const checksum = generated_header.computeChecksum(code);
    const header = try generated_header.renderFromBuildInfoWithChecksum(allocator, checksum);
    defer allocator.free(header);

    const content = try std.mem.concat(allocator, u8, &.{ header, code });
    defer allocator.free(content);

    if (std.fs.path.dirname(path)) |parent| {
        try cwd.createDirPath(io, parent);
    }

    const output_file = try cwd.createFile(io, path, .{});
    defer output_file.close(io);
    try output_file.writeStreamingAll(io, content);
    std.log.info("Wrote '{s}'", .{path});
}

/// Returns true when `path` already holds generated code with the same checksum
/// as `raw_code`.
///
/// A missing file is simply "changed". Any other read failure is reported so a
/// broken existence check cannot silently degrade into overwriting the file on
/// every run.
pub fn isUnchanged(
    allocator: std.mem.Allocator,
    io: std.Io,
    cwd: std.Io.Dir,
    path: []const u8,
    raw_code: []const u8,
) !bool {
    const existing = cwd.readFileAlloc(io, path, allocator, .unlimited) catch |err| switch (err) {
        error.FileNotFound => return false,
        else => {
            std.log.warn("Could not read existing '{s}' to check for changes ({}); it will be overwritten", .{ path, err });
            return false;
        },
    };
    defer allocator.free(existing);

    return !generated_header.hasChanged(existing, raw_code);
}
